version: '3'
services:
  postgres:
    image: mdillon/postgis:9.2
    hostname: postgres
    env_file: .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ckan_postgres_db:/var/lib/postgresql/data

  solr:
    image: ckan/solr
    hostname: solr

  datapusher:
    build: datapusher
    hostname: datapusher

  redis:
    image: redis:4

  ckan:
    build: .
    hostname: ckan
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - solr
      - redis
    volumes:
      - ./ckan/configs.ini:/etc/ckan/default/configs.ini
      - ckan_config:/etc/ckan/default
      - ckan_filestore_data:/var/lib/ckan/default
    env_file: .env

volumes:
  ckan_postgres_db:
  ckan_config:
  ckan_filestore_data: